#!/bin/sh -ex

[ -z "$(git status --porcelain)" ] || exit 1

ver_cur="$(awk -F'"' '/^version[[:space:]]*=/ { print $2 }' bobcat-sdk/Cargo.toml | tail -n1)"

ver_minor="$(echo "$ver_cur" | cut -d. -f2)"

ver_next="0.$(echo $ver_minor '+ 1' | bc).0"

files=$(find -name Cargo.toml -maxdepth 2)

sed -i "s/$ver_cur/$ver_next/g" $files

git add $files

git commit -m 'Release new version'

cargo publish -n

git checkout -b release-$ver_next

git tag -a $ver_next

# Any patches for bugs are cherry picked into this release, with a nightly build being made
# every day using the CI that can be pointed to. The minor releasing needs to be done here.

git push -a

git checkout trunk
