[workspace]
resolver = "3"
members = [
	"bobcat-maths",
	"bobcat-storage",
	"bobcat-entry",
	"bobcat-panic",
	"bobcat-proxy",
	"bobcat-cd",
	"bobcat-sdk",
	"bobcat-interfaces",
	"bobcat-call",
	"bobcat-console",
	"bobcat-events",
	"bobcat-precompiles",
	"bobcat-maths-zone",
	"bobcat-features",
	"bobcat-host",
	"bobcat-alloc"
]
exclude = ["fuzz"]

[workspace.dependencies]
proptest = { version = "1.8.0" }
const-hex = { version = ">=1.0.1", default-features = false }
array-concat = "0.5.5"
paste = "1.0.15"
keccak-const = ">=0.2.0"
