[profile.default]
out = "out"
libs = ["forge-libs"]
test = "e2e-test"
gas_snapshot_emit = true
fs_permissions = [
	{ access = "read", path = "e2e-test/chainlink-vrf-test.wasm"},
	{ access = "read", path = "e2e-test/transient-exchange.wasm"},
	{ access = "read", path = "e2e-test/console-log-txt.wasm"},
	{ access = "read", path = "e2e-test/counter.wasm"},
	{ access = "read", path = "e2e-test/mul-div.wasm"},
	{ access = "read", path = "e2e-test/beacon.wasm"},
	{ access = "read", path = "e2e-test/panic-revert.wasm"},
	{ access = "read", path = "e2e-test/eip1967-proxy.wasm"},
	{ access = "read", path = "e2e-test/reverts-bubbling-up.wasm"},
	{ access = "read", path = "e2e-test/proxy-predicts-create2.wasm"},
	{ access = "read", path = "e2e-test/precompiles.wasm"},
	{ access = "read", path = "e2e-test/slot-map.wasm"},
	{ access = "read", path = "e2e-test/safe-erc20.wasm"},
	{ access = "read", path = "e2e-test/tracing-counter.wasm" },
	{ access = "read", path = "e2e-test/panic-trace.wasm" },
	{ access = "read", path = "e2e-test/superposition-precompiles/precompiles-ed25519.wasm" },
	{ access = "read", path = "e2e-test/precompiles.wasm" },
	{ access = "read", path = "e2e-test/math-example.wasm" },
]

[lint]
exclude_lints = ["mixed-case-function"]
