[package]
name = "bobcat-panic"
version = "0.7.17"
edition = "2024"
license = "MIT"
description = "Bobcat utilities with a panic handler on Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_panic"

[features]
alloc = []
console = ["alloc", "bobcat-host/console"]
std = ["proptest"]
panic-revert = ["panic"]
panic-loc = ["panic"]
panic-trace = ["panic"]
panic = []
msg-on-sdk-err = ["panic"]
proptest = ["dep:proptest"]

[dependencies]
bobcat-host = { version = "0.7.17", path = "../bobcat-host" }
const-hex.workspace = true
paste.workspace = true
proptest = { workspace = true, optional = true }
