[package]
name = "bobcat-panic"
version = "0.8.1"
edition = "2024"
license = "MIT"
description = "Bobcat utilities with a panic handler on Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_panic"

[features]
default = ["std"]
alloc = []
console = ["alloc", "bobcat-host/console"]
std = []
panic-revert = ["panic"]
panic-loc = ["panic"]
panic-trace = ["panic"]
panic-code = ["panic"]
panic = []
msg-on-sdk-err = ["panic"]
proptest = ["dep:proptest"]
detailed-errors = ["panic"]

[dependencies]
bobcat-host = { version = "0.8.1", path = "../bobcat-host" }
const-hex.workspace = true
paste.workspace = true
proptest = { workspace = true, optional = true }
