[package]
name = "bobcat-precompiles"
version = "0.9.6"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for using precompiles with Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[features]
default = ["alloc"]
ed25519-dalek = ["dep:ed25519-dalek", "sha512"]
alloc = ["bobcat-call/alloc"]
tickmath-local = ["dep:markovgeist-precompiles-tickmath"]
sha512 = ["dep:sha2"]
dont-define-symbols = ["bobcat-call/dont-define-symbols"]
borsh = ["dep:borsh"]
serde = ["dep:serde"]

[dependencies]
array-concat.workspace = true
bobcat-call = { version = "0.9.6", path = "../bobcat-call", default-features = false }
bobcat-cd = { version = "0.9.6", path = "../bobcat-cd", default-features = false }
bobcat-maths = { version = "0.9.6", path = "../bobcat-maths", default-features = false }
bobcat-storage = { version = "0.9.6", path = "../bobcat-storage", default-features = false }
ed25519-dalek = { version = ">=3.0.0", default-features = false, features = ["digest"], optional = true }
sha2 = { version = ">=0.11.0", default-features = false, optional = true }
markovgeist-precompiles-tickmath = { version = "0.1.4", optional = true }
serde = { version = ">=1.0.0", default-features = false, features = ["derive"], optional = true }
borsh = { version = ">=1.0.0", default-features = false, features = ["derive"], optional = true }
const-hex.workspace = true

[dev-dependencies]
alloy-sol-macro = "1.4.1"
alloy-sol-types = "1.4.1"
alloy-primitives = "1.4.1"
proptest.workspace = true
bobcat-maths = { version = "0.9.6", path = "../bobcat-maths", features = ["proptest"] }
