[package]
name = "bobcat-precompiles"
version = "0.7.41"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for using precompiles with Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[features]
ed25519-dalek = ["dep:ed25519-dalek", "sha512"]
alloc = ["bobcat-call/alloc"]
tickmath-local = ["dep:markovgeist-precompiles-tickmath"]
sha512 = ["dep:sha2"]
dont-define-symbols = ["bobcat-call/dont-define-symbols",]

[dependencies]
array-concat.workspace = true
bobcat-call = { version = "0.7.41", path = "../bobcat-call" }
bobcat-cd = { version = "0.7.41", path = "../bobcat-cd" }
bobcat-maths = { version = "0.7.41", path = "../bobcat-maths" }
bobcat-storage = { version = "0.7.41", path = "../bobcat-storage" }
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["digest"], optional = true }
sha2 = { version = ">=0.10.9", default-features = false, optional = true }
markovgeist-precompiles-tickmath = { version = "0.1.4", optional = true }
