[workspace]
exclude = ["fuzz"]

[package]
name = "bobcat-examples-004"
version = "0.1.0"
edition = "2024"

[lib]
name = "libbozo"

[dependencies]
array-concat = "0.5.5"
bobcat-sdk = { path = "../../bobcat-sdk", default-features = false, features = ["panic-revert", "alloc"] }
concat-arrays = "0.1.2"
const-hex = { version = "1.17.0", default-features = false, features = ["alloc"] }
mini-alloc = "1.0.0"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
lto = "fat"
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
codegen-units = 16
panic = "unwind"
opt-level = "z"
incremental = true

[features]
std = ["bobcat-sdk/std"]
inline-maths = ["bobcat-sdk/alloy-enabled"]
arbitrary = ["bobcat-sdk/arbitrary"]

[dev-dependencies]
proptest = "1.9.0"
proptest-derive = "0.7.0"

[dev-dependencies.bobcat-sdk]
path = "../../bobcat-sdk"
features = ["std", "alloc", "alloy-enabled", "proptest"]
