[package]
name = "bobcat-features"
version = "0.7.34"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for feature flagged release on Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_features"

[dependencies]
bobcat-call = { version = "0.7.34", path = "../bobcat-call" }
bobcat-entry = { version = "0.7.34", path = "../bobcat-entry" }
bobcat-interfaces = { version = "0.7.34", path = "../bobcat-interfaces" }
bobcat-storage = { version = "0.7.34", path = "../bobcat-storage" }
paste.workspace = true

[features]
std = ["bobcat-storage/std", "bobcat-entry/std"]
mutex = ["bobcat-storage/mutex"]
alloy-enabled = ["bobcat-entry/alloy-enabled", "bobcat-storage/alloy-enabled"]
dont-define-symbols = ["bobcat-entry/dont-define-symbols"]
msg-on-sdk-err = ["bobcat-call/msg-on-sdk-err"]
panic = ["bobcat-call/panic"]
panic-rever = ["bobcat-call/panic-revert"]

[dev-dependencies]
bobcat-host = { path = "../bobcat-host" }
