[package]
name = "bobcat-features"
version = "0.7.10"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for feature flagged release on Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_features"

[dependencies]
bobcat-storage = { version = "0.7.10", path = "../bobcat-storage" }
paste.workspace = true

[features]
std = ["bobcat-storage/std"]
proptest = ["bobcat-storage/proptest"]
mutex = ["bobcat-storage/mutex"]
