[package]
name = "bobcat-call"
version = "0.9.2"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for calling contracts with Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_call"

[features]
default = ["alloc"]
alloc = []
dont-define-symbols = ["bobcat-entry/dont-define-symbols"]
panic = ["bobcat-panic/panic"]
panic-revert = ["bobcat-panic/panic-revert"]
panic-code = ["bobcat-panic/panic-code"]
msg-on-sdk-err = ["bobcat-panic/msg-on-sdk-err"]
detailed-errors = ["bobcat-panic/detailed-errors"]

[dependencies]
bobcat-entry = { version = "0.9.2", path = "../bobcat-entry", default-features = false }
bobcat-host = { version = "0.9.2", path = "../bobcat-host", default-features = false }
bobcat-maths = { version = "0.9.2", path = "../bobcat-maths", default-features = false }
bobcat-panic = { version = "0.9.2", path = "../bobcat-panic", default-features = false }
const-hex.workspace = true
paste.workspace = true
