[package]
name = "bobcat-call"
version = "0.7.12"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for calling contracts with Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_call"

[features]
alloc = []
dont-define-symbols = ["bobcat-entry/dont-define-symbols"]
panic = ["bobcat-panic/panic"]
panic-revert = ["bobcat-panic/panic-revert"]
msg-on-sdk-err = ["bobcat-panic/msg-on-sdk-err"]

[dependencies]
bobcat-entry = { version = "0.7.12", path = "../bobcat-entry" }
bobcat-maths = { version = "0.7.12", path = "../bobcat-maths" }
bobcat-panic = { version = "0.7.12", path = "../bobcat-panic" }
paste.workspace = true
