[package]
name = "bobcat-host"
version = "0.7.35"
edition = "2024"
license = "MIT"
description = "Functions for interacting with the host with bobcat-sdk"
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[dependencies]
keccak-const.workspace = true
const-hex.workspace = true

[features]
std = ["const-hex/std"]
mutex = ["std"]
console = []
