[workspace]

[package]
name = "reference"
version = "0.1.11"
edition = "2024"

[dependencies]
stylus-sdk = { version = "0.10.9" }

[lib]
name = "libreference"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "reference"
path = "src/main.rs"

[features]
export-abi = []
contract-client-gen = []

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "z"
