[workspace]
resolver = "3"
members = [
	"chainlink-vrf-test",
	"console-log-txt",
	"transient-exchange",
	"counter",
	"mul-div",
	"beacon",
	"panic-revert",
	"eip1967-proxy",
	"reverts-bubbling-up",
	"proxy-predicts-create2",
	"precompiles",
	"slot-map",
	"safe-erc20",
	"tracing-counter",
	"features",
	"math-example"
]

[workspace.dependencies]
bobcat-sdk = { path = "../bobcat-sdk", features = ["alloc", "panic-revert", "msg-on-sdk-err", "console"] }
mini-alloc = "1.0.0"

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "unwind"
opt-level = "z"
