[package]
name = "bobcat-console"
version = "0.9.2"
edition = "2024"
license = "MIT"
description = "bobcat-sdk console makes printing easy with Arbitrum Stylus, using a macro."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[dependencies]
bobcat-host = { version = "0.9.2", path = "../bobcat-host", features = ["console"] }
