[package]
name = "bobcat-cd"
version = "0.7.20"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for accessing calldata on Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_cd"

[dependencies]
bobcat-maths = { version = "0.7.20", path = "../bobcat-maths" }
array-concat = { workspace = true }
proptest = { workspace = true, optional = true }
bobcat-storage = { version = "0.7.20", path = "../bobcat-storage" }
const-hex = { workspace = true }
