[package]
name = "bobcat-cd"
version = "0.9.3"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for accessing calldata on Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_cd"

[dependencies]
bobcat-maths = { version = "0.9.3", path = "../bobcat-maths", default-features = false }
array-concat = { workspace = true }
proptest = { workspace = true, optional = true }
bobcat-storage = { version = "0.9.3", path = "../bobcat-storage", default-features = false }
const-hex = { workspace = true }
