package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/stylus-developers-guild/bobcat-sdk/examples/004-bozo/graph/model"
)

// PostComment is the resolver for the postComment field.
func (r *mutationResolver) PostComment(ctx context.Context, content string, rr string, ss string, v int32) (*bool, error) {
	panic(fmt.Errorf("not implemented: PostComment - postComment"))
}

// GameInfo is the resolver for the gameInfo field.
func (r *queryResolver) GameInfo(ctx context.Context) (*model.GameInfo, error) {
	panic(fmt.Errorf("not implemented: GameInfo - gameInfo"))
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context) ([]*model.Comment, error) {
	return []*model.Comment{
		{"Hello", "world", "0x8b62653ba29d21922e140f9df6747eea6f2e6cf8facba3e96469d4931269b57f"},
	}, nil
}

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) ([]*model.Player, error) {
	panic(fmt.Errorf("not implemented: Players - players"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
