[package]
name = "bobcat-create"
version = "0.7.37"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for using CREATE1 and CREATE2 on Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_create"

[dependencies]
bobcat-proxy = { version = "0.7.37", path = "../bobcat-proxy" }
bobcat-maths = { version = "0.7.37", path = "../bobcat-maths" }
bobcat-storage = { version = "0.7.37", path = "../bobcat-storage" }
array-concat.workspace = true
bobcat-host = { version = "0.7.37", path = "../bobcat-host" }

[features]
alloc = []
std = ["alloc"]
