[package]
name = "bobcat-sdk"
version = "0.7.25"
edition = "2024"
license = "MIT"
description = "bobcat-sdk is a codesize efficient Arbitrum Stylus SDK"
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_sdk"

[dependencies]
bobcat-create = { version = "0.7.25", path = "../bobcat-create" }
bobcat-entry = { version = "0.7.25", path = "../bobcat-entry" }
bobcat-maths = { version = "0.7.25", path = "../bobcat-maths" }
bobcat-panic = { version = "0.7.25", path = "../bobcat-panic", optional = true }
bobcat-proxy = { version = "0.7.25", path = "../bobcat-proxy" }
bobcat-storage = { version = "0.7.25", path = "../bobcat-storage" }
bobcat-cd = { version = "0.7.25", path = "../bobcat-cd" }
bobcat-interfaces = { version = "0.7.25", path = "../bobcat-interfaces" }
bobcat-call = { version = "0.7.25", path = "../bobcat-call" }
bobcat-console = { version = "0.7.25", path = "../bobcat-console", optional = true }
bobcat-events = { version = "0.7.25", path = "../bobcat-events" }
bobcat-precompiles = { version = "0.7.25", path = "../bobcat-precompiles" }
bobcat-maths-zone = { version = "0.7.25", path = "../bobcat-maths-zone" }
bobcat-features = { version = "0.7.25", path = "../bobcat-features" }
bobcat-host = { version = "0.7.25", path = "../bobcat-host" }
bobcat-alloc = { version = "0.7.25", path = "../bobcat-alloc", optional = true }

[features]
std = [
	"bobcat-create/std",
	"bobcat-entry/std",
	"bobcat-maths/std",
	"bobcat-panic/std",
	"bobcat-storage/std"
]
alloc = [
	"bobcat-create/alloc",
	"bobcat-entry/alloc",
	"bobcat-call/alloc",
	"bobcat-panic/alloc",
	"bobcat-events/alloc",
	"bobcat-maths/alloc",
	"bobcat-precompiles/alloc",
	"dep:bobcat-alloc"
]
serde = ["bobcat-maths/serde"]
borsh = ["bobcat-maths/borsh"]
console = ["dep:bobcat-console", "bobcat-panic/console", "bobcat-host/console"]
arbitrary = ["bobcat-maths/arbitrary"]
proptest = ["bobcat-maths/proptest", "bobcat-storage/proptest"]
alloy-enabled = [
	"bobcat-maths/alloy-enabled",
	"bobcat-entry/alloy-enabled"
]
panic = ["bobcat-panic/panic"]
panic-revert = ["panic", "bobcat-panic/panic-revert"]
panic-loc = ["panic", "bobcat-panic/panic-loc"]
panic-trace = ["panic", "bobcat-panic/panic-trace"]
dont-define-symbols = [
	"bobcat-entry/dont-define-symbols",
	"bobcat-call/dont-define-symbols",
	"bobcat-features/dont-define-symbols"
]
ruint-enabled = ["bobcat-maths/ruint-enabled"]
msg-on-sdk-err = [
	"bobcat-panic/msg-on-sdk-err",
	"bobcat-maths/msg-on-sdk-err",
	"bobcat-call/msg-on-sdk-err",
	"bobcat-features/msg-on-sdk-err"
]
wasm-bindgen = ["bobcat-maths/wasm-bindgen"]
wasm-bindgen-wasi = ["bobcat-maths/wasm-bindgen-wasi"]
ed25519-dalek = ["bobcat-precompiles/ed25519-dalek"]
shadow = ["bobcat-events/shadow"]
mutex = ["bobcat-storage/mutex"]
detailed-errors = ["bobcat-call/detailed-errors"]
tickmath-local = ["bobcat-precompiles/tickmath-local"]
