[package]
name = "bobcat-sdk"
version = "0.6.3"
edition = "2024"
license = "MIT"
description = "bobcat-sdk is a codesize efficient Arbitrum Stylus SDK"
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_sdk"

[dependencies]
bobcat-create = { version = "0.6.3", path = "../bobcat-create" }
bobcat-entry = { version = "0.6.3", path = "../bobcat-entry" }
bobcat-maths = { version = "0.6.3", path = "../bobcat-maths" }
bobcat-panic = { version = "0.6.3", path = "../bobcat-panic", optional = true }
bobcat-proxy = { version = "0.6.3", path = "../bobcat-proxy" }
bobcat-storage = { version = "0.6.3", path = "../bobcat-storage" }
bobcat-cd = { version = "0.6.3", path = "../bobcat-cd" }
bobcat-interfaces = { version = "0.6.3", path = "../bobcat-interfaces" }
bobcat-call = { version = "0.6.3", path = "../bobcat-call" }
bobcat-console = { version = "0.6.3", path = "../bobcat-console", optional = true }
bobcat-events = { version = "0.6.3", path = "../bobcat-events" }

[features]
std = [
	"bobcat-create/std",
	"bobcat-entry/std",
	"bobcat-maths/std",
	"bobcat-panic/std",
	"bobcat-storage/std",
]
borsh = ["bobcat-maths/borsh"]
alloc = [
	"bobcat-create/alloc",
	"bobcat-entry/alloc",
	"bobcat-maths/alloc",
	"bobcat-call/alloc",
	"bobcat-console",
	"bobcat-panic/alloc",
	"bobcat-events/alloc"
]
console = ["bobcat-panic/console"]
arbitrary-enabled = ["bobcat-maths/arbitrary-enabled"]
proptest-enabled = ["bobcat-maths/proptest-enabled"]
proptest = ["proptest-enabled", "bobcat-storage/proptest"]
panic = ["bobcat-panic"]
panic-revert = ["bobcat-panic", "bobcat-panic/panic-revert"]
dont-define-symbols = [
	"bobcat-entry/dont-define-symbols",
	"bobcat-call/dont-define-symbols"
]
ruint-enabled = ["bobcat-maths/ruint-enabled"]
