[package]
name = "bobcat-sdk"
version = "0.9.4"
edition = "2024"
license = "MIT"
description = "bobcat-sdk is a codesize efficient Arbitrum Stylus SDK"
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_sdk"

[dependencies]
bobcat-create = { version = "0.9.4", path = "../bobcat-create", default-features = false }
bobcat-entry = { version = "0.9.4", path = "../bobcat-entry", default-features = false }
bobcat-maths = { version = "0.9.4", path = "../bobcat-maths", default-features = false }
bobcat-panic = { version = "0.9.4", path = "../bobcat-panic", optional = true, default-features = false }
bobcat-proxy = { version = "0.9.4", path = "../bobcat-proxy", default-features = false }
bobcat-storage = { version = "0.9.4", path = "../bobcat-storage", default-features = false }
bobcat-cd = { version = "0.9.4", path = "../bobcat-cd", default-features = false }
bobcat-interfaces = { version = "0.9.4", path = "../bobcat-interfaces", default-features = false }
bobcat-call = { version = "0.9.4", path = "../bobcat-call", default-features = false }
bobcat-console = { version = "0.9.4", path = "../bobcat-console", optional = true, default-features = false }
bobcat-events = { version = "0.9.4", path = "../bobcat-events", default-features = false }
bobcat-precompiles = { version = "0.9.4", path = "../bobcat-precompiles", default-features = false }
bobcat-maths-zone = { version = "0.9.4", path = "../bobcat-maths-zone", optional = true, default-features = false }
bobcat-features = { version = "0.9.4", path = "../bobcat-features", default-features = false }
bobcat-host = { version = "0.9.4", path = "../bobcat-host", default-features = false }
bobcat-alloc = { version = "0.9.4", path = "../bobcat-alloc", optional = true, default-features = false }

[features]
default = ["std", "borsh", "serde", "ed25519-dalek", "sha512", "tickmath-local"]
std = [
	"bobcat-create/std",
	"bobcat-entry/std",
	"bobcat-maths/std",
	"bobcat-panic/std",
	"bobcat-storage/std",
	"bobcat-host/std",
	"bobcat-interfaces/alloc"
]
alloc = [
	"bobcat-create/alloc",
	"bobcat-entry/alloc",
	"bobcat-call/alloc",
	"bobcat-panic/alloc",
	"bobcat-events/alloc",
	"bobcat-maths/alloc",
	"bobcat-precompiles/alloc",
	"dep:bobcat-alloc",
	"bobcat-interfaces/alloc"
]
serde = ["bobcat-maths/serde", "bobcat-precompiles/serde"]
borsh = ["bobcat-maths/borsh", "bobcat-precompiles/serde"]
console = ["dep:bobcat-console", "bobcat-panic/console", "bobcat-host/console"]
arbitrary = ["bobcat-maths/arbitrary"]
proptest = ["bobcat-maths/proptest", "bobcat-storage/proptest"]
alloy-enabled = [
	"bobcat-maths/alloy-enabled",
	"bobcat-entry/alloy-enabled"
]
panic = ["bobcat-panic/panic"]
panic-revert = ["panic", "bobcat-panic/panic-revert"]
panic-loc = ["panic", "bobcat-panic/panic-loc"]
panic-trace = ["panic", "bobcat-panic/panic-trace"]
dont-define-symbols = [
	"bobcat-entry/dont-define-symbols",
	"bobcat-call/dont-define-symbols",
	"bobcat-features/dont-define-symbols",
	"bobcat-precompiles/dont-define-symbols"
]
ruint-enabled = ["bobcat-maths/ruint-enabled"]
msg-on-sdk-err = [
	"bobcat-panic/msg-on-sdk-err",
	"bobcat-maths/msg-on-sdk-err",
	"bobcat-call/msg-on-sdk-err",
	"bobcat-features/msg-on-sdk-err"
]
wasm-bindgen = ["bobcat-maths/wasm-bindgen"]
wasm-bindgen-wasi = ["bobcat-maths/wasm-bindgen-wasi"]
ed25519-dalek = ["bobcat-precompiles/ed25519-dalek"]
shadow = ["bobcat-events/shadow"]
mutex = ["bobcat-storage/mutex"]
detailed-errors = ["bobcat-call/detailed-errors"]
tickmath-local = ["bobcat-precompiles/tickmath-local"]
maths-zone = ["dep:bobcat-maths-zone"]
sha512 = ["bobcat-precompiles/sha512"]
