[package]
name = "bobcat-maths"
version = "0.7.41"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities performing codesize efficient math on Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_maths"

[dependencies]
num-traits = { version = ">=0.2.19", default-features = false }
proptest = { workspace = true, optional = true }
arbitrary = { version = ">=1.4.2", optional = true, features = ["derive"] }
proptest-derive = { version = ">=0.6.0", optional = true }
alloy-primitives = { version = ">=1.0.0", default-features = false, optional = true }
borsh = { version = ">=1.0.0", default-features = false, features = ["derive"], optional = true }
mutants = "0.0.3"
cfg-if = "1.0.3"
const-hex.workspace = true
paste.workspace = true
array-concat.workspace = true
serde = { version = ">=1.0.0", default-features = false, features = ["derive"], optional = true }
bobcat-panic = { version = "0.7.41", path = "../bobcat-panic" }
clap = { version = ">=4.0.0", optional = true }
wasm-bindgen = { version = ">=0.2.0", optional = true, default-features = false }
bobcat-host = { version = "0.7.41", path = "../bobcat-host" }

[features]
std = ["alloc", "dep:clap"]
wasm-bindgen = ["dep:wasm-bindgen", "alloc"]
wasm-bindgen-wasi = ["dep:wasm-bindgen", "alloc"]
alloc = []
proptest = ["std", "dep:proptest-derive", "dep:proptest"]
arbitrary = ["std", "dep:arbitrary"]
alloy-enabled = ["dep:alloy-primitives"]
ruint-enabled = ["alloy-enabled"]
panic = ["bobcat-panic/panic"]
panic-revert = ["bobcat-panic/panic-revert"]
panic-code = ["bobcat-panic/panic-code"]
msg-on-sdk-err = ["bobcat-panic/msg-on-sdk-err"]
detailed-errors = ["bobcat-panic/detailed-errors"]
