[package]
name = "bobcat-proxy"
version = "0.7.14"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities for creating proxy code on Arbitrum Stylus."
homepage = "https://bobcat.so"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[lib]
name = "bobcat_proxy"

[dependencies]
array-concat = { workspace = true }
const-hex = { workspace = true }
bobcat-maths = { version = "0.7.14", path = "../bobcat-maths" }
bobcat-interfaces = { version = "0.7.14", path = "../bobcat-interfaces" }
