[package]
name = "bobcat-events"
version = "0.7.48"
edition = "2024"
license = "MIT"
description = "bobcat-sdk utilities performing event emission on Arbitrum Stylus."
homepage = "https://stylusup.sh"
repository = "https://github.com/stylus-developers-guild/bobcat-sdk"

[dependencies]
array-concat.workspace = true
bobcat-maths = { version = "0.7.48", path = "../bobcat-maths" }
bobcat-host = { version = "0.7.48", path = "../bobcat-host" }

[features]
alloc = ["bobcat-maths/alloc"]
shadow = []
